/**
 * Single source of truth for the facts that appear in more than one place:
 * the site, the one-page résumé and the long CV.
 *
 * These three had drifted apart — the site said 27+ client systems while the
 * résumé said 30+ production applications, and the job title was "Freelance
 * Software Engineer" in one document and "Associate Web Developer" in
 * another. Anything stated as fact about Akash belongs here, and every
 * surface reads from it rather than restating it.
 *
 * Fields marked RESUME ONLY are not rendered on the site. They live here so
 * the documents can be generated from the same data later.
 */

/** Total experience includes trainee/intern work (confirmed by Akash, 25 September 2026). */
export const identity = {
	name: "Akash Damle",
	/** The one job title. Used everywhere; do not vary it per document. */
	title: "Backend Engineer",
	/** Longer form for the hero and metadata. */
	positioning: "Backend engineer, 8+ years of total experience.",
	location: "Badlapur, India",
	availability: "Available for remote roles",
	/** Shown in the footer and useful on a résumé for remote applications. */
	workingStyle: "Working remotely",
} as const

export const contact = {
	email: "akashdamle07@gmail.com",
	github: "https://github.com/code-kasha",
	linkedin: "https://www.linkedin.com/in/akash-damle-58a808258/",
	site: "https://www.akashdamle.in",
	/** RESUME ONLY. Already public via the linked PDF. */
	phone: "+91 98333 58619",
	/** The one-page résumé, generated by `pnpm resume`. */
	resumePdf: "/Resume.pdf",
	/** The long résumé, generated by `pnpm resume`. */
	resumeLongPdf: "/Resume(Long).pdf",
} as const

/**
 * RESUME ONLY. The one-page résumé uses `short`; the long one uses every
 * paragraph of `long`.
 */
export const resumeSummary = {
	short:
		"Backend engineer with 8+ years of total experience, building and operating systems in Django and Node/TypeScript. I ship the unglamorous parts properly: typed API contracts, integration tests that run in CI, and deployments I maintain myself.",
	long: [
		"Backend engineer with 8+ years of total experience, building and operating systems in Django and Node/TypeScript. On client work I own the whole backend, sometimes as the only engineer and sometimes alongside a frontend developer, which means I have owned schema design, API surface, deployment and support rather than one slice of it.",
		"Recent work has focused on making that ownership repeatable: typed API contracts generated from a single schema definition, integration test suites that run against a real database in CI, and infrastructure I can rebuild from scratch.",
	],
} as const

export const summary =
	"I build the unglamorous parts properly — typed APIs, real test suites, deployments that hold up on a Tuesday afternoon."

/**
 * One sentence, used for the meta description, OpenGraph and Twitter cards.
 * It lived inline in app/layout.tsx three times over, which is how the years
 * figure drifted out of step with the site in the first place.
 */
export const metaDescription =
	"Backend engineer with 8+ years of total experience, building systems in Django, Node.js and TypeScript."

/**
 * Every number here has to survive being asked "measured how?".
 *
 * The unverifiable claims that used to sit on both the site and the résumé
 * ("2000+ users", "20-35% performance improvement") are deliberately absent:
 * nothing backs them, and a reviewer who probes one of them discredits the
 * rest. Replacements are traceable — the coverage figure is checkable in the
 * maxread-api repo, the client count comes from the CV's own 27+ CRM
 * deployments.
 */
export const stats = [
	{ value: "100%", label: "Endpoint coverage on my latest API" },
	{ value: "27+", label: "Client systems built and self-hosted" },
	{ value: "8+", label: "Years of total experience" },
	{ value: "3", label: "Stacks in production: Django, Node, TS" },
] as const

export const skills = [
	{ group: "Backend", items: ["Django", "DRF", "Node.js", "Express", "REST"] },
	{ group: "Languages", items: ["Python", "TypeScript", "JavaScript", "SQL"] },
	{ group: "Data", items: ["PostgreSQL", "MongoDB", "Redis", "Query tuning"] },
	{ group: "Platform", items: ["Docker", "CI/CD", "Linux", "AWS", "Vercel"] },
	{ group: "Quality", items: ["Vitest", "Pytest", "Zod", "OpenAPI"] },
	{ group: "Frontend", items: ["React", "Next.js", "Tailwind", "Redux"] },
] as const

export type Role = {
	/** Display form, e.g. "2021 — Present". */
	period: string
	/** RESUME ONLY. ISO months, so documents can format dates themselves. */
	from: string
	to: string | null
	role: string
	company: string
	description: string
	tags: string[]
	/** RESUME ONLY. Bullets for the one-page résumé. */
	highlights: string[]
	/** RESUME ONLY. Opening line for the long résumé, if any. */
	intro?: string
	/** RESUME ONLY. Bullets for the long résumé. */
	details: string[]
	/** RESUME ONLY. Stack line for the long résumé. */
	stack: string[]
}

export const experience: Role[] = [
	{
		period: "2021 — Present",
		from: "2021-03",
		to: null,
		role: "Freelance Software Engineer",
		company: "Independent · Remote",
		description:
			"Design, build and host Django CRM systems for schools, clinics and small businesses. Employee management, payroll, attendance and analytics, running on self-managed Linux servers with ongoing support.",
		tags: ["Django", "PostgreSQL", "Linux", "Self-hosted"],
		highlights: [
			"Built and delivered Django CRM systems for 27+ clients across schools, clinics and small businesses, covering employee management, payroll, attendance tracking and reporting.",
			"Own the full lifecycle for each deployment: schema design, REST API, provisioning, release and ongoing support.",
			"Run the infrastructure directly: self-managed Linux servers with PostgreSQL, rather than handing off to a platform team.",
			"Sole engineer on some engagements; on others, owned the backend alongside a frontend developer. Worked directly with non-technical stakeholders to scope and prioritise.",
		],
		intro:
			"Django CRM and internal-tooling work for small organisations (schools, clinics and SMBs), delivered end to end and supported on an ongoing basis.",
		details: [
			"Delivered 27+ client systems, each covering some combination of employee management, payroll calculation, attendance tracking, performance review and reporting.",
			"Designed the relational schema and REST API for each deployment, and built the admin and reporting surfaces on top.",
			"Provisioned and maintained self-managed Linux servers running PostgreSQL, including backups, TLS and upgrades. Hosting is part of the engagement rather than the client's problem.",
			"Worked directly with non-technical stakeholders to scope requirements, agree priorities and run acceptance.",
			"Also delivered custom websites with Django and Django CMS for clients whose needs stopped short of a full system.",
		],
		stack: ["Django", "Python", "PostgreSQL", "Django CMS", "Linux", "Nginx", "Gunicorn"],
	},
	{
		period: "2018 — 2021",
		from: "2018-08",
		to: "2021-02",
		role: "Junior Software Developer",
		company: "Matalli Infotech · Dombivli",
		description:
			"Built and maintained internal web applications on Django 2.2 LTS. Wrote unit and database tests, implemented CI/CD pipelines, and managed deployments across AWS and Heroku with minimal downtime.",
		tags: ["Django", "CI/CD", "AWS", "Testing"],
		highlights: [
			"Built and maintained internal web applications on Django 2.2 LTS as part of a small engineering team.",
			"Wrote unit and database-level tests, and introduced CI/CD pipelines to shorten the release cycle.",
			"Managed deployments to Linux servers, AWS and Heroku, and handled production fixes with minimal downtime.",
		],
		intro: "First engineering role, on a small team maintaining internal web applications.",
		details: [
			"Built and maintained internal applications on Django 2.2 LTS.",
			"Wrote unit and database-level tests to keep regressions out of releases.",
			"Implemented and worked with CI/CD pipelines to shorten the release cycle.",
			"Managed deployments across Linux servers, AWS and Heroku.",
			"Delivered production patches and bug fixes with minimal downtime.",
			"Learned project structure, code organisation and review practice in a team setting, and used Git throughout for collaboration.",
		],
		stack: ["Django", "Python", "Git", "Linux", "AWS", "Heroku", "CI/CD"],
	},
]

/** RESUME ONLY. */
export const education = [
	{
		qualification: "B.Sc, Computer Science",
		institution: "P V G's College of Science",
		from: "2014",
		to: "2018",
	},
] as const

/** RESUME ONLY. Shown on the long résumé. */
export const certifications = [
	{ course: "Full Stack Development", provider: "Internshala", period: "Oct 2025 – Apr 2026" },
	{ course: "Master the Coding Interview: Data Structures + Algorithms", provider: "Udemy", period: "Apr 2025 – Jan 2026" },
	{ course: "The Complete JavaScript Course: From Zero to Expert", provider: "Udemy", period: "Jun 2025 – Nov 2025" },
	{ course: "Microservices with Node.js and React", provider: "Udemy", period: "Apr 2024 – Sep 2025" },
	{ course: "The Complete Full-Stack Web Development Bootcamp", provider: "Udemy", period: "Jun 2023 – Feb 2024" },
	{ course: "Python Django: The Practical Guide", provider: "Udemy", period: "Jan 2021 – Aug 2021" },
] as const

/** Flat list for the ticker. */
export const skillTicker = skills.flatMap((group) => group.items)
